import { CountriesCode } from '../../core/interfaces/countries-code';

export const curransie: CountriesCode[] = [
  {
    countryName: 'United Arab Emirates',
    code: 'AE',
    currency: 'AED',
    currencyName: 'United Arab Emirates Dirham',
  },
  {
    countryName: 'Afghanistan',
    code: 'AF',
    currency: 'AFN',
    currencyName: 'Afghan Afghani',
  },
  {
    countryName: 'Albania',
    code: 'AL',
    currency: 'ALL',
    currencyName: 'Albanian Lek',
  },
  {
    countryName: 'Armenia',
    code: 'AM',
    currency: 'AMD',
    currencyName: 'Armenian Dram',
  },
  {
    countryName: 'Netherlands Antilles',
    code: 'AN',
    currency: 'ANG',
    currencyName: 'Netherlands Antillean Guilder',
  },
  {
    countryName: 'Angola',
    code: 'AO',
    currency: 'AOA',
    currencyName: 'Angolan Kwanza',
  },
  {
    countryName: 'Argentina',
    code: 'AR',
    currency: 'ARS',
    currencyName: 'Argentine Peso',
  },
  {
    countryName: 'Australia',
    code: 'AU',
    currency: 'AUD',
    currencyName: 'Australian Dollar',
  },
  {
    countryName: 'Aruba',
    code: 'AW',
    currency: 'AWG',
    currencyName: 'Aruban Florin',
  },
  {
    countryName: 'Azerbaijan',
    code: 'AZ',
    currency: 'AZN',
    currencyName: 'Azerbaijani Manat',
  },
  {
    countryName: 'Bosnia and Herzegovina',
    code: 'BA',
    currency: 'BAM',
    currencyName: 'Bosnia-Herzegovina Convertible Mark',
  },
  {
    countryName: 'Barbados',
    code: 'BB',
    currency: 'BBD',
    currencyName: 'Barbadian Dollar',
  },
  {
    countryName: 'Bangladesh',
    code: 'BD',
    currency: 'BDT',
    currencyName: 'Bangladeshi Taka',
  },
  {
    countryName: 'Bulgaria',
    code: 'BG',
    currency: 'BGN',
    currencyName: 'Bulgarian Lev',
  },
  {
    countryName: 'Bahrain',
    code: 'BH',
    currency: 'BHD',
    currencyName: 'Bahraini Dinar',
  },
  {
    countryName: 'Burundi',
    code: 'BI',
    currency: 'BIF',
    currencyName: 'Burundian Franc',
  },
  {
    countryName: 'Bermuda',
    code: 'BM',
    currency: 'BMD',
    currencyName: 'Bermudan Dollar',
  },
  {
    countryName: 'Brunei',
    code: 'BN',
    currency: 'BND',
    currencyName: 'Brunei Dollar',
  },
  {
    countryName: 'Bolivia',
    code: 'BO',
    currency: 'BOB',
    currencyName: 'Bolivian Boliviano',
  },
  {
    countryName: 'Brazil',
    code: 'BR',
    currency: 'BRL',
    currencyName: 'Brazilian Real',
  },
  {
    countryName: 'Bahamas',
    code: 'BS',
    currency: 'BSD',
    currencyName: 'Bahamian Dollar',
  },
  {
    countryName: 'Botswana',
    code: 'BW',
    currency: 'BWP',
    currencyName: 'Botswanan Pula',
  },
  {
    countryName: 'Belarus',
    code: 'BY',
    currency: 'BYN',
    currencyName: 'Belarusian Ruble',
  },
  {
    countryName: 'Belize',
    code: 'BZ',
    currency: 'BZD',
    currencyName: 'Belize Dollar',
  },
  {
    countryName: 'Canada',
    code: 'CA',
    currency: 'CAD',
    currencyName: 'Canadian Dollar',
  },
  {
    countryName: 'Congo (DRC)',
    code: 'CD',
    currency: 'CDF',
    currencyName: 'Congolese Franc',
  },
  {
    countryName: 'Switzerland',
    code: 'CH',
    currency: 'CHF',
    currencyName: 'Swiss Franc',
  },
  {
    countryName: 'Chile',
    code: 'CL',
    currency: 'CLP',
    currencyName: 'Chilean Peso',
  },
  {
    countryName: 'China',
    code: 'CN',
    currency: 'CNY',
    currencyName: 'Chinese Yuan',
  },
  {
    countryName: 'Colombia',
    code: 'CO',
    currency: 'COP',
    currencyName: 'Colombian Peso',
  },
  {
    countryName: 'Costa Rica',
    code: 'CR',
    currency: 'CRC',
    currencyName: 'Costa Rican Colón',
  },
  {
    countryName: 'Cuba',
    code: 'CU',
    currency: 'CUP',
    currencyName: 'Cuban Peso',
  },
  {
    countryName: 'Cape Verde',
    code: 'CV',
    currency: 'CVE',
    currencyName: 'Cape Verdean Escudo',
  },
  {
    countryName: 'Czech Republic',
    code: 'CZ',
    currency: 'CZK',
    currencyName: 'Czech Koruna',
  },
  {
    countryName: 'Djibouti',
    code: 'DJ',
    currency: 'DJF',
    currencyName: 'Djiboutian Franc',
  },
  {
    countryName: 'Denmark',
    code: 'DK',
    currency: 'DKK',
    currencyName: 'Danish Krone',
  },
  {
    countryName: 'Dominican Republic',
    code: 'DO',
    currency: 'DOP',
    currencyName: 'Dominican Peso',
  },
  {
    countryName: 'Algeria',
    code: 'DZ',
    currency: 'DZD',
    currencyName: 'Algerian Dinar',
  },
  {
    countryName: 'Egypt',
    code: 'EG',
    currency: 'EGP',
    currencyName: 'Egyptian Pound',
  },
  {
    countryName: 'Eritrea',
    code: 'ER',
    currency: 'ERN',
    currencyName: 'Eritrean Nakfa',
  },
  {
    countryName: 'Ethiopia',
    code: 'ET',
    currency: 'ETB',
    currencyName: 'Ethiopian Birr',
  },
  {
    countryName: 'European Union',
    code: 'EU',
    currency: 'EUR',
    currencyName: 'Euro',
  },
  {
    countryName: 'Fiji',
    code: 'FJ',
    currency: 'FJD',
    currencyName: 'Fijian Dollar',
  },
  {
    countryName: 'Falkland Islands',
    code: 'FK',
    currency: 'FKP',
    currencyName: 'Falkland Islands Pound',
  },
  {
    countryName: 'United Kingdom',
    code: 'GB',
    currency: 'GBP',
    currencyName: 'British Pound Sterling',
  },
  {
    countryName: 'Georgia',
    code: 'GE',
    currency: 'GEL',
    currencyName: 'Georgian Lari',
  },
  {
    countryName: 'Ghana',
    code: 'GH',
    currency: 'GHS',
    currencyName: 'Ghanaian Cedi',
  },
  {
    countryName: 'Gibraltar',
    code: 'GI',
    currency: 'GIP',
    currencyName: 'Gibraltar Pound',
  },
  {
    countryName: 'Gambia',
    code: 'GM',
    currency: 'GMD',
    currencyName: 'Gambian Dalasi',
  },
  {
    countryName: 'Guinea',
    code: 'GN',
    currency: 'GNF',
    currencyName: 'Guinean Franc',
  },
  {
    countryName: 'Guatemala',
    code: 'GT',
    currency: 'GTQ',
    currencyName: 'Guatemalan Quetzal',
  },
  {
    countryName: 'Guyana',
    code: 'GY',
    currency: 'GYD',
    currencyName: 'Guyanese Dollar',
  },
  {
    countryName: 'Hong Kong',
    code: 'HK',
    currency: 'HKD',
    currencyName: 'Hong Kong Dollar',
  },
  {
    countryName: 'Honduras',
    code: 'HN',
    currency: 'HNL',
    currencyName: 'Honduran Lempira',
  },
  {
    countryName: 'Haiti',
    code: 'HT',
    currency: 'HTG',
    currencyName: 'Haitian Gourde',
  },
  {
    countryName: 'Hungary',
    code: 'HU',
    currency: 'HUF',
    currencyName: 'Hungarian Forint',
  },
  {
    countryName: 'Indonesia',
    code: 'ID',
    currency: 'IDR',
    currencyName: 'Indonesian Rupiah',
  },
  {
    countryName: 'Israel',
    code: 'IL',
    currency: 'ILS',
    currencyName: 'Israeli New Shekel',
  },
  {
    countryName: 'India',
    code: 'IN',
    currency: 'INR',
    currencyName: 'Indian Rupee',
  },
  {
    countryName: 'Iraq',
    code: 'IQ',
    currency: 'IQD',
    currencyName: 'Iraqi Dinar',
  },
  {
    countryName: 'Iran',
    code: 'IR',
    currency: 'IRR',
    currencyName: 'Iranian Rial',
  },
  {
    countryName: 'Iceland',
    code: 'IS',
    currency: 'ISK',
    currencyName: 'Icelandic Króna',
  },
  {
    countryName: 'Jamaica',
    code: 'JM',
    currency: 'JMD',
    currencyName: 'Jamaican Dollar',
  },
  {
    countryName: 'Jordan',
    code: 'JO',
    currency: 'JOD',
    currencyName: 'Jordanian Dinar',
  },
  {
    countryName: 'Japan',
    code: 'JP',
    currency: 'JPY',
    currencyName: 'Japanese Yen',
  },
  {
    countryName: 'Kenya',
    code: 'KE',
    currency: 'KES',
    currencyName: 'Kenyan Shilling',
  },
  {
    countryName: 'Kyrgyzstan',
    code: 'KG',
    currency: 'KGS',
    currencyName: 'Kyrgyzstani Som',
  },
  {
    countryName: 'Cambodia',
    code: 'KH',
    currency: 'KHR',
    currencyName: 'Cambodian Riel',
  },
  {
    countryName: 'Comoros',
    code: 'KM',
    currency: 'KMF',
    currencyName: 'Comorian Franc',
  },
  {
    countryName: 'North Korea',
    code: 'KP',
    currency: 'KPW',
    currencyName: 'North Korean Won',
  },
  {
    countryName: 'South Korea',
    code: 'KR',
    currency: 'KRW',
    currencyName: 'South Korean Won',
  },
  {
    countryName: 'Kuwait',
    code: 'KW',
    currency: 'KWD',
    currencyName: 'Kuwaiti Dinar',
  },
  {
    countryName: 'Cayman Islands',
    code: 'KY',
    currency: 'KYD',
    currencyName: 'Cayman Islands Dollar',
  },
  {
    countryName: 'Kazakhstan',
    code: 'KZ',
    currency: 'KZT',
    currencyName: 'Kazakhstani Tenge',
  },
  {
    countryName: 'Laos',
    code: 'LA',
    currency: 'LAK',
    currencyName: 'Lao Kip',
  },
  {
    countryName: 'Lebanon',
    code: 'LB',
    currency: 'LBP',
    currencyName: 'Lebanese Pound',
  },
  {
    countryName: 'Sri Lanka',
    code: 'LK',
    currency: 'LKR',
    currencyName: 'Sri Lankan Rupee',
  },
  {
    countryName: 'Liberia',
    code: 'LR',
    currency: 'LRD',
    currencyName: 'Liberian Dollar',
  },
  {
    countryName: 'Lesotho',
    code: 'LS',
    currency: 'LSL',
    currencyName: 'Lesotho Loti',
  },
  {
    countryName: 'Libya',
    code: 'LY',
    currency: 'LYD',
    currencyName: 'Libyan Dinar',
  },
  {
    countryName: 'Morocco',
    code: 'MA',
    currency: 'MAD',
    currencyName: 'Moroccan Dirham',
  },
  {
    countryName: 'Moldova',
    code: 'MD',
    currency: 'MDL',
    currencyName: 'Moldovan Leu',
  },
  {
    countryName: 'Madagascar',
    code: 'MG',
    currency: 'MGA',
    currencyName: 'Malagasy Ariary',
  },
  {
    countryName: 'North Macedonia',
    code: 'MK',
    currency: 'MKD',
    currencyName: 'Macedonian Denar',
  },
  {
    countryName: 'Myanmar',
    code: 'MM',
    currency: 'MMK',
    currencyName: 'Myanmar Kyat',
  },
  {
    countryName: 'Mongolia',
    code: 'MN',
    currency: 'MNT',
    currencyName: 'Mongolian Tögrög',
  },
  {
    countryName: 'Macau',
    code: 'MO',
    currency: 'MOP',
    currencyName: 'Macanese Pataca',
  },
  {
    countryName: 'Mauritania',
    code: 'MR',
    currency: 'MRU',
    currencyName: 'Mauritanian Ouguiya',
  },
  {
    countryName: 'Mauritius',
    code: 'MU',
    currency: 'MUR',
    currencyName: 'Mauritian Rupee',
  },
  {
    countryName: 'Maldives',
    code: 'MV',
    currency: 'MVR',
    currencyName: 'Maldivian Rufiyaa',
  },
  {
    countryName: 'Malawi',
    code: 'MW',
    currency: 'MWK',
    currencyName: 'Malawian Kwacha',
  },
  {
    countryName: 'Mexico',
    code: 'MX',
    currency: 'MXN',
    currencyName: 'Mexican Peso',
  },
  {
    countryName: 'Malaysia',
    code: 'MY',
    currency: 'MYR',
    currencyName: 'Malaysian Ringgit',
  },
  {
    countryName: 'Mozambique',
    code: 'MZ',
    currency: 'MZN',
    currencyName: 'Mozambican Metical',
  },
  {
    countryName: 'Namibia',
    code: 'NA',
    currency: 'NAD',
    currencyName: 'Namibian Dollar',
  },
  {
    countryName: 'Nigeria',
    code: 'NG',
    currency: 'NGN',
    currencyName: 'Nigerian Naira',
  },
  {
    countryName: 'Nicaragua',
    code: 'NI',
    currency: 'NIO',
    currencyName: 'Nicaraguan Córdoba',
  },
  {
    countryName: 'Norway',
    code: 'NO',
    currency: 'NOK',
    currencyName: 'Norwegian Krone',
  },
  {
    countryName: 'Nepal',
    code: 'NP',
    currency: 'NPR',
    currencyName: 'Nepalese Rupee',
  },
  {
    countryName: 'New Zealand',
    code: 'NZ',
    currency: 'NZD',
    currencyName: 'New Zealand Dollar',
  },
  {
    countryName: 'Oman',
    code: 'OM',
    currency: 'OMR',
    currencyName: 'Omani Rial',
  },
  {
    countryName: 'Panama',
    code: 'PA',
    currency: 'PAB',
    currencyName: 'Panamanian Balboa',
  },
  {
    countryName: 'Peru',
    code: 'PE',
    currency: 'PEN',
    currencyName: 'Peruvian Sol',
  },
  {
    countryName: 'Papua New Guinea',
    code: 'PG',
    currency: 'PGK',
    currencyName: 'Papua New Guinean Kina',
  },
  {
    countryName: 'Philippines',
    code: 'PH',
    currency: 'PHP',
    currencyName: 'Philippine Peso',
  },
  {
    countryName: 'Pakistan',
    code: 'PK',
    currency: 'PKR',
    currencyName: 'Pakistani Rupee',
  },
  {
    countryName: 'Poland',
    code: 'PL',
    currency: 'PLN',
    currencyName: 'Polish Złoty',
  },
  {
    countryName: 'Paraguay',
    code: 'PY',
    currency: 'PYG',
    currencyName: 'Paraguayan Guaraní',
  },
  {
    countryName: 'Qatar',
    code: 'QA',
    currency: 'QAR',
    currencyName: 'Qatari Rial',
  },
  {
    countryName: 'Romania',
    code: 'RO',
    currency: 'RON',
    currencyName: 'Romanian Leu',
  },
  {
    countryName: 'Serbia',
    code: 'RS',
    currency: 'RSD',
    currencyName: 'Serbian Dinar',
  },
  {
    countryName: 'Russia',
    code: 'RU',
    currency: 'RUB',
    currencyName: 'Russian Ruble',
  },
  {
    countryName: 'Rwanda',
    code: 'RW',
    currency: 'RWF',
    currencyName: 'Rwandan Franc',
  },
  {
    countryName: 'Saudi Arabia',
    code: 'SA',
    currency: 'SAR',
    currencyName: 'Saudi Riyal',
  },
  {
    countryName: 'Solomon Islands',
    code: 'SB',
    currency: 'SBD',
    currencyName: 'Solomon Islands Dollar',
  },
  {
    countryName: 'Seychelles',
    code: 'SC',
    currency: 'SCR',
    currencyName: 'Seychellois Rupee',
  },
  {
    countryName: 'Sudan',
    code: 'SD',
    currency: 'SDG',
    currencyName: 'Sudanese Pound',
  },
  {
    countryName: 'Sweden',
    code: 'SE',
    currency: 'SEK',
    currencyName: 'Swedish Krona',
  },
  {
    countryName: 'Singapore',
    code: 'SG',
    currency: 'SGD',
    currencyName: 'Singapore Dollar',
  },
  {
    countryName: 'Saint Helena',
    code: 'SH',
    currency: 'SHP',
    currencyName: 'Saint Helena Pound',
  },
  {
    countryName: 'Sierra Leone',
    code: 'SL',
    currency: 'SLL',
    currencyName: 'Sierra Leonean Leone',
  },
  {
    countryName: 'Somalia',
    code: 'SO',
    currency: 'SOS',
    currencyName: 'Somali Shilling',
  },
  {
    countryName: 'Suriname',
    code: 'SR',
    currency: 'SRD',
    currencyName: 'Surinamese Dollar',
  },
  {
    countryName: 'South Sudan',
    code: 'SS',
    currency: 'SSP',
    currencyName: 'South Sudanese Pound',
  },
  {
    countryName: 'Sao Tome and Principe',
    code: 'ST',
    currency: 'STN',
    currencyName: 'São Tomé and Príncipe Dobra',
  },
  {
    countryName: 'El Salvador',
    code: 'SV',
    currency: 'SVC',
    currencyName: 'Salvadoran Colón',
  },
  {
    countryName: 'Syria',
    code: 'SY',
    currency: 'SYP',
    currencyName: 'Syrian Pound',
  },
  {
    countryName: 'Eswatini',
    code: 'SZ',
    currency: 'SZL',
    currencyName: 'Swazi Lilangeni',
  },
  {
    countryName: 'Thailand',
    code: 'TH',
    currency: 'THB',
    currencyName: 'Thai Baht',
  },
  {
    countryName: 'Tajikistan',
    code: 'TJ',
    currency: 'TJS',
    currencyName: 'Tajikistani Somoni',
  },
  {
    countryName: 'Turkmenistan',
    code: 'TM',
    currency: 'TMT',
    currencyName: 'Turkmenistani Manat',
  },
  {
    countryName: 'Tunisia',
    code: 'TN',
    currency: 'TND',
    currencyName: 'Tunisian Dinar',
  },
  {
    countryName: 'Tonga',
    code: 'TO',
    currency: 'TOP',
    currencyName: 'Tongan Paʻanga',
  },
  {
    countryName: 'Turkey',
    code: 'TR',
    currency: 'TRY',
    currencyName: 'Turkish Lira',
  },
  {
    countryName: 'Trinidad and Tobago',
    code: 'TT',
    currency: 'TTD',
    currencyName: 'Trinidad and Tobago Dollar',
  },
  {
    countryName: 'Taiwan',
    code: 'TW',
    currency: 'TWD',
    currencyName: 'New Taiwan Dollar',
  },
  {
    countryName: 'Tanzania',
    code: 'TZ',
    currency: 'TZS',
    currencyName: 'Tanzanian Shilling',
  },
  {
    countryName: 'Ukraine',
    code: 'UA',
    currency: 'UAH',
    currencyName: 'Ukrainian Hryvnia',
  },
  {
    countryName: 'Uganda',
    code: 'UG',
    currency: 'UGX',
    currencyName: 'Ugandan Shilling',
  },
  {
    countryName: 'United States',
    code: 'US',
    currency: 'USD',
    currencyName: 'United States Dollar',
  },
  {
    countryName: 'Uruguay',
    code: 'UY',
    currency: 'UYU',
    currencyName: 'Uruguayan Peso',
  },
  {
    countryName: 'Uzbekistan',
    code: 'UZ',
    currency: 'UZS',
    currencyName: 'Uzbekistani Som',
  },
  {
    countryName: 'Venezuela',
    code: 'VE',
    currency: 'VES',
    currencyName: 'Venezuelan Bolívar Soberano',
  },
  {
    countryName: 'Vietnam',
    code: 'VN',
    currency: 'VND',
    currencyName: 'Vietnamese Đồng',
  },
  {
    countryName: 'Vanuatu',
    code: 'VU',
    currency: 'VUV',
    currencyName: 'Vanuatu Vatu',
  },
  {
    countryName: 'Samoa',
    code: 'WS',
    currency: 'WST',
    currencyName: 'Samoan Tala',
  },
  {
    countryName: 'Central African States',
    code: 'CF',
    currency: 'XAF',
    currencyName: 'Central African CFA Franc',
  },
  {
    countryName: 'Eastern Caribbean States',
    code: 'AG',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
  },
  {
    countryName: 'IMF (Special Drawing Rights)',
    code: 'IM',
    currency: 'XDR',
    currencyName: 'Special Drawing Rights',
  },
  {
    countryName: 'West African States',
    code: 'BF',
    currency: 'XOF',
    currencyName: 'West African CFA Franc',
  },
  {
    countryName: 'French Polynesia',
    code: 'PF',
    currency: 'XPF',
    currencyName: 'CFP Franc',
  },
  {
    countryName: 'Yemen',
    code: 'YE',
    currency: 'YER',
    currencyName: 'Yemeni Rial',
  },
  {
    countryName: 'South Africa',
    code: 'ZA',
    currency: 'ZAR',
    currencyName: 'South African Rand',
  },
  {
    countryName: 'Zambia',
    code: 'ZM',
    currency: 'ZMW',
    currencyName: 'Zambian Kwacha',
  },
];
