import { CountriesCode } from '../../core/interfaces/countries-code';

export const curransie: CountriesCode[] = [
  { countryName: 'Egypt', code: 'EG', currency: 'EGP', currencyName: 'Egyptian Pound' },
  {
    countryName: 'United States',
    code: 'US',
    currency: 'USD',
    currencyName: 'United States Dollar',
  },
  { countryName: 'European Union', code: 'EU', currency: 'EUR', currencyName: 'Euro' },
  {
    countryName: 'United Kingdom',
    code: 'GB',
    currency: 'GBP',
    currencyName: 'British Pound Sterling',
  },
  { countryName: 'Japan', code: 'JP', currency: 'JPY', currencyName: 'Japanese Yen' },
  { countryName: 'Switzerland', code: 'CH', currency: 'CHF', currencyName: 'Swiss Franc' },
  { countryName: 'Canada', code: 'CA', currency: 'CAD', currencyName: 'Canadian Dollar' },
  { countryName: 'Australia', code: 'AU', currency: 'AUD', currencyName: 'Australian Dollar' },
  {
    countryName: 'United Arab Emirates',
    code: 'AE',
    currency: 'AED',
    currencyName: 'United Arab Emirates Dirham',
  },
  { countryName: 'Denmark', code: 'DK', currency: 'DKK', currencyName: 'Danish Krone' },
  { countryName: 'Kuwait', code: 'KW', currency: 'KWD', currencyName: 'Kuwaiti Dinar' },
  { countryName: 'Saudi Arabia', code: 'SA', currency: 'SAR', currencyName: 'Saudi Riyal' },
  { countryName: 'Oman', code: 'OM', currency: 'OMR', currencyName: 'Omani Rial' },
  { countryName: 'Bahrain', code: 'BH', currency: 'BHD', currencyName: 'Bahraini Dinar' },
  { countryName: 'China', code: 'CN', currency: 'CNY', currencyName: 'Chinese Yuan' },

  { countryName: 'Afghanistan', code: 'AF', currency: 'AFN', currencyName: 'Afghan Afghani' },
  { countryName: 'Albania', code: 'AL', currency: 'ALL', currencyName: 'Albanian Lek' },
  { countryName: 'Algeria', code: 'DZ', currency: 'DZD', currencyName: 'Algerian Dinar' },
  { countryName: 'Angola', code: 'AO', currency: 'AOA', currencyName: 'Angolan Kwanza' },
  { countryName: 'Argentina', code: 'AR', currency: 'ARS', currencyName: 'Argentine Peso' },
  { countryName: 'Armenia', code: 'AM', currency: 'AMD', currencyName: 'Armenian Dram' },
  { countryName: 'Aruba', code: 'AW', currency: 'AWG', currencyName: 'Aruban Florin' },
  { countryName: 'Azerbaijan', code: 'AZ', currency: 'AZN', currencyName: 'Azerbaijani Manat' },
  { countryName: 'Bahamas', code: 'BS', currency: 'BSD', currencyName: 'Bahamian Dollar' },
  { countryName: 'Bangladesh', code: 'BD', currency: 'BDT', currencyName: 'Bangladeshi Taka' },
  { countryName: 'Barbados', code: 'BB', currency: 'BBD', currencyName: 'Barbadian Dollar' },
  { countryName: 'Belarus', code: 'BY', currency: 'BYN', currencyName: 'Belarusian Ruble' },
  { countryName: 'Belize', code: 'BZ', currency: 'BZD', currencyName: 'Belize Dollar' },
  { countryName: 'Bermuda', code: 'BM', currency: 'BMD', currencyName: 'Bermudan Dollar' },
  { countryName: 'Bolivia', code: 'BO', currency: 'BOB', currencyName: 'Bolivian Boliviano' },
  {
    countryName: 'Bosnia and Herzegovina',
    code: 'BA',
    currency: 'BAM',
    currencyName: 'Bosnia-Herzegovina Convertible Mark',
  },
  { countryName: 'Botswana', code: 'BW', currency: 'BWP', currencyName: 'Botswanan Pula' },
  { countryName: 'Brazil', code: 'BR', currency: 'BRL', currencyName: 'Brazilian Real' },
  { countryName: 'Brunei', code: 'BN', currency: 'BND', currencyName: 'Brunei Dollar' },
  { countryName: 'Bulgaria', code: 'BG', currency: 'BGN', currencyName: 'Bulgarian Lev' },
  { countryName: 'Burundi', code: 'BI', currency: 'BIF', currencyName: 'Burundian Franc' },
  { countryName: 'Bhutan', code: 'BT', currency: 'BTN', currencyName: 'Bhutanese Ngultrum' },
  { countryName: 'Cambodia', code: 'KH', currency: 'KHR', currencyName: 'Cambodian Riel' },
  { countryName: 'Cape Verde', code: 'CV', currency: 'CVE', currencyName: 'Cape Verdean Escudo' },
  {
    countryName: 'Cayman Islands',
    code: 'KY',
    currency: 'KYD',
    currencyName: 'Cayman Islands Dollar',
  },
  { countryName: 'Chile', code: 'CL', currency: 'CLP', currencyName: 'Chilean Peso' },
  {
    countryName: 'China (Offshore)',
    code: 'CN',
    currency: 'CNH',
    currencyName: 'Chinese Yuan (Offshore)',
  },
  { countryName: 'Colombia', code: 'CO', currency: 'COP', currencyName: 'Colombian Peso' },
  { countryName: 'Comoros', code: 'KM', currency: 'KMF', currencyName: 'Comorian Franc' },
  { countryName: 'Congo (DRC)', code: 'CD', currency: 'CDF', currencyName: 'Congolese Franc' },
  { countryName: 'Costa Rica', code: 'CR', currency: 'CRC', currencyName: 'Costa Rican Colón' },
  { countryName: 'Croatia', code: 'HR', currency: 'HRK', currencyName: 'Croatian Kuna' },
  { countryName: 'Cuba', code: 'CU', currency: 'CUP', currencyName: 'Cuban Peso' },
  { countryName: 'Czech Republic', code: 'CZ', currency: 'CZK', currencyName: 'Czech Koruna' },
  { countryName: 'Djibouti', code: 'DJ', currency: 'DJF', currencyName: 'Djiboutian Franc' },
  {
    countryName: 'Dominican Republic',
    code: 'DO',
    currency: 'DOP',
    currencyName: 'Dominican Peso',
  },
  { countryName: 'Eritrea', code: 'ER', currency: 'ERN', currencyName: 'Eritrean Nakfa' },
  { countryName: 'Ethiopia', code: 'ET', currency: 'ETB', currencyName: 'Ethiopian Birr' },
  {
    countryName: 'Falkland Islands',
    code: 'FK',
    currency: 'FKP',
    currencyName: 'Falkland Islands Pound',
  },
  { countryName: 'Faroe Islands', code: 'FO', currency: 'FOK', currencyName: 'Faroese Króna' },
  { countryName: 'Fiji', code: 'FJ', currency: 'FJD', currencyName: 'Fijian Dollar' },
  { countryName: 'Gambia', code: 'GM', currency: 'GMD', currencyName: 'Gambian Dalasi' },
  { countryName: 'Georgia', code: 'GE', currency: 'GEL', currencyName: 'Georgian Lari' },
  { countryName: 'Ghana', code: 'GH', currency: 'GHS', currencyName: 'Ghanaian Cedi' },
  { countryName: 'Gibraltar', code: 'GI', currency: 'GIP', currencyName: 'Gibraltar Pound' },
  { countryName: 'Guernsey', code: 'GG', currency: 'GGP', currencyName: 'Guernsey Pound' },
  { countryName: 'Guatemala', code: 'GT', currency: 'GTQ', currencyName: 'Guatemalan Quetzal' },
  { countryName: 'Guinea', code: 'GN', currency: 'GNF', currencyName: 'Guinean Franc' },
  { countryName: 'Guyana', code: 'GY', currency: 'GYD', currencyName: 'Guyanese Dollar' },
  { countryName: 'Haiti', code: 'HT', currency: 'HTG', currencyName: 'Haitian Gourde' },
  { countryName: 'Honduras', code: 'HN', currency: 'HNL', currencyName: 'Honduran Lempira' },
  { countryName: 'Hong Kong', code: 'HK', currency: 'HKD', currencyName: 'Hong Kong Dollar' },
  { countryName: 'Hungary', code: 'HU', currency: 'HUF', currencyName: 'Hungarian Forint' },
  { countryName: 'Iceland', code: 'IS', currency: 'ISK', currencyName: 'Icelandic Króna' },
  { countryName: 'India', code: 'IN', currency: 'INR', currencyName: 'Indian Rupee' },
  { countryName: 'Indonesia', code: 'ID', currency: 'IDR', currencyName: 'Indonesian Rupiah' },
  { countryName: 'Iran', code: 'IR', currency: 'IRR', currencyName: 'Iranian Rial' },
  { countryName: 'Iraq', code: 'IQ', currency: 'IQD', currencyName: 'Iraqi Dinar' },
  { countryName: 'Isle of Man', code: 'IM', currency: 'IMP', currencyName: 'Isle of Man Pound' },
  { countryName: 'Israel', code: 'IL', currency: 'ILS', currencyName: 'Israeli New Shekel' },
  { countryName: 'Jamaica', code: 'JM', currency: 'JMD', currencyName: 'Jamaican Dollar' },
  { countryName: 'Jersey', code: 'JE', currency: 'JEP', currencyName: 'Jersey Pound' },
  { countryName: 'Jordan', code: 'JO', currency: 'JOD', currencyName: 'Jordanian Dinar' },
  { countryName: 'Kazakhstan', code: 'KZ', currency: 'KZT', currencyName: 'Kazakhstani Tenge' },
  { countryName: 'Kenya', code: 'KE', currency: 'KES', currencyName: 'Kenyan Shilling' },
  { countryName: 'Kiribati', code: 'KI', currency: 'KID', currencyName: 'Kiribati Dollar' },
  { countryName: 'Kyrgyzstan', code: 'KG', currency: 'KGS', currencyName: 'Kyrgyzstani Som' },
  { countryName: 'Laos', code: 'LA', currency: 'LAK', currencyName: 'Lao Kip' },
  { countryName: 'Lebanon', code: 'LB', currency: 'LBP', currencyName: 'Lebanese Pound' },
  { countryName: 'Lesotho', code: 'LS', currency: 'LSL', currencyName: 'Lesotho Loti' },
  { countryName: 'Liberia', code: 'LR', currency: 'LRD', currencyName: 'Liberian Dollar' },
  { countryName: 'Libya', code: 'LY', currency: 'LYD', currencyName: 'Libyan Dinar' },
  { countryName: 'Macau', code: 'MO', currency: 'MOP', currencyName: 'Macanese Pataca' },
  { countryName: 'Madagascar', code: 'MG', currency: 'MGA', currencyName: 'Malagasy Ariary' },
  { countryName: 'Malawi', code: 'MW', currency: 'MWK', currencyName: 'Malawian Kwacha' },
  { countryName: 'Malaysia', code: 'MY', currency: 'MYR', currencyName: 'Malaysian Ringgit' },
  { countryName: 'Maldives', code: 'MV', currency: 'MVR', currencyName: 'Maldivian Rufiyaa' },
  { countryName: 'Mauritania', code: 'MR', currency: 'MRU', currencyName: 'Mauritanian Ouguiya' },
  { countryName: 'Mauritius', code: 'MU', currency: 'MUR', currencyName: 'Mauritian Rupee' },
  { countryName: 'Mexico', code: 'MX', currency: 'MXN', currencyName: 'Mexican Peso' },
  { countryName: 'Moldova', code: 'MD', currency: 'MDL', currencyName: 'Moldovan Leu' },
  { countryName: 'Mongolia', code: 'MN', currency: 'MNT', currencyName: 'Mongolian Tögrög' },
  { countryName: 'Morocco', code: 'MA', currency: 'MAD', currencyName: 'Moroccan Dirham' },
  { countryName: 'Mozambique', code: 'MZ', currency: 'MZN', currencyName: 'Mozambican Metical' },
  { countryName: 'Myanmar', code: 'MM', currency: 'MMK', currencyName: 'Myanmar Kyat' },
  { countryName: 'Namibia', code: 'NA', currency: 'NAD', currencyName: 'Namibian Dollar' },
  { countryName: 'Nepal', code: 'NP', currency: 'NPR', currencyName: 'Nepalese Rupee' },
  {
    countryName: 'Netherlands Antilles',
    code: 'AN',
    currency: 'ANG',
    currencyName: 'Netherlands Antillean Guilder',
  },
  { countryName: 'New Zealand', code: 'NZ', currency: 'NZD', currencyName: 'New Zealand Dollar' },
  { countryName: 'Nicaragua', code: 'NI', currency: 'NIO', currencyName: 'Nicaraguan Córdoba' },
  { countryName: 'Nigeria', code: 'NG', currency: 'NGN', currencyName: 'Nigerian Naira' },
  { countryName: 'North Korea', code: 'KP', currency: 'KPW', currencyName: 'North Korean Won' },
  { countryName: 'North Macedonia', code: 'MK', currency: 'MKD', currencyName: 'Macedonian Denar' },
  { countryName: 'Norway', code: 'NO', currency: 'NOK', currencyName: 'Norwegian Krone' },
  { countryName: 'Pacific Franc', code: 'XPF', currency: 'XPF', currencyName: 'CFP Franc' },
  { countryName: 'Pakistan', code: 'PK', currency: 'PKR', currencyName: 'Pakistani Rupee' },
  { countryName: 'Palau', code: 'PW', currency: 'USD', currencyName: 'US Dollar' }, // Placeholder for USD
  { countryName: 'Panama', code: 'PA', currency: 'PAB', currencyName: 'Panamanian Balboa' },
  {
    countryName: 'Papua New Guinea',
    code: 'PG',
    currency: 'PGK',
    currencyName: 'Papua New Guinean Kina',
  },
  { countryName: 'Paraguay', code: 'PY', currency: 'PYG', currencyName: 'Paraguayan Guaraní' },
  { countryName: 'Peru', code: 'PE', currency: 'PEN', currencyName: 'Peruvian Sol' },
  { countryName: 'Philippines', code: 'PH', currency: 'PHP', currencyName: 'Philippine Peso' },
  { countryName: 'Poland', code: 'PL', currency: 'PLN', currencyName: 'Polish Złoty' },
  { countryName: 'Qatar', code: 'QA', currency: 'QAR', currencyName: 'Qatari Riyal' },
  { countryName: 'Romania', code: 'RO', currency: 'RON', currencyName: 'Romanian Leu' },
  { countryName: 'Russia', code: 'RU', currency: 'RUB', currencyName: 'Russian Ruble' },
  { countryName: 'Rwanda', code: 'RW', currency: 'RWF', currencyName: 'Rwandan Franc' },
  { countryName: 'Saint Helena', code: 'SH', currency: 'SHP', currencyName: 'Saint Helena Pound' },
  { countryName: 'Samoa', code: 'WS', currency: 'WST', currencyName: 'Samoan Tala' },
  {
    countryName: 'São Tomé and Príncipe',
    code: 'ST',
    currency: 'STN',
    currencyName: 'São Tomé and Príncipe Dobra',
  },
  { countryName: 'Serbia', code: 'RS', currency: 'RSD', currencyName: 'Serbian Dinar' },
  { countryName: 'Seychelles', code: 'SC', currency: 'SCR', currencyName: 'Seychellois Rupee' },
  {
    countryName: 'Sierra Leone',
    code: 'SL',
    currency: 'SLE',
    currencyName: 'Sierra Leonean Leone',
  },
  {
    countryName: 'Sierra Leone (Old)',
    code: 'SL',
    currency: 'SLL',
    currencyName: 'Sierra Leonean Leone (Old)',
  },
  { countryName: 'Singapore', code: 'SG', currency: 'SGD', currencyName: 'Singapore Dollar' },
  {
    countryName: 'Solomon Islands',
    code: 'SB',
    currency: 'SBD',
    currencyName: 'Solomon Islands Dollar',
  },
  { countryName: 'Somalia', code: 'SO', currency: 'SOS', currencyName: 'Somali Shilling' },
  { countryName: 'South Africa', code: 'ZA', currency: 'ZAR', currencyName: 'South African Rand' },
  { countryName: 'South Korea', code: 'KR', currency: 'KRW', currencyName: 'South Korean Won' },
  { countryName: 'South Sudan', code: 'SS', currency: 'SSP', currencyName: 'South Sudanese Pound' },
  { countryName: 'Sri Lanka', code: 'LK', currency: 'LKR', currencyName: 'Sri Lankan Rupee' },
  { countryName: 'Sudan', code: 'SD', currency: 'SDG', currencyName: 'Sudanese Pound' },
  { countryName: 'Suriname', code: 'SR', currency: 'SRD', currencyName: 'Surinamese Dollar' },
  { countryName: 'Swaziland', code: 'SZ', currency: 'SZL', currencyName: 'Swazi Lilangeni' },
  { countryName: 'Sweden', code: 'SE', currency: 'SEK', currencyName: 'Swedish Krona' },
  { countryName: 'Syria', code: 'SY', currency: 'SYP', currencyName: 'Syrian Pound' },
  { countryName: 'Taiwan', code: 'TW', currency: 'TWD', currencyName: 'New Taiwan Dollar' },
  { countryName: 'Tajikistan', code: 'TJ', currency: 'TJS', currencyName: 'Tajikistani Somoni' },
  { countryName: 'Tanzania', code: 'TZ', currency: 'TZS', currencyName: 'Tanzanian Shilling' },
  { countryName: 'Thailand', code: 'TH', currency: 'THB', currencyName: 'Thai Baht' },
  { countryName: 'Tonga', code: 'TO', currency: 'TOP', currencyName: 'Tongan Paʻanga' },
  {
    countryName: 'Trinidad and Tobago',
    code: 'TT',
    currency: 'TTD',
    currencyName: 'Trinidad and Tobago Dollar',
  },
  { countryName: 'Tunisia', code: 'TN', currency: 'TND', currencyName: 'Tunisian Dinar' },
  { countryName: 'Turkey', code: 'TR', currency: 'TRY', currencyName: 'Turkish Lira' },
  { countryName: 'Turkmenistan', code: 'TM', currency: 'TMT', currencyName: 'Turkmenistan Manat' },
  { countryName: 'Tuvalu', code: 'TV', currency: 'TVD', currencyName: 'Tuvaluan Dollar' },
  { countryName: 'Uganda', code: 'UG', currency: 'UGX', currencyName: 'Ugandan Shilling' },
  { countryName: 'Ukraine', code: 'UA', currency: 'UAH', currencyName: 'Ukrainian Hryvnia' },
  { countryName: 'Uruguay', code: 'UY', currency: 'UYU', currencyName: 'Uruguayan Peso' },
  { countryName: 'Uzbekistan', code: 'UZ', currency: 'UZS', currencyName: 'Uzbekistani Som' },
  { countryName: 'Vanuatu', code: 'VU', currency: 'VUV', currencyName: 'Vanuatu Vatu' },
  { countryName: 'Venezuela', code: 'VE', currency: 'VES', currencyName: 'Venezuelan Bolívar' },
  { countryName: 'Vietnam', code: 'VN', currency: 'VND', currencyName: 'Vietnamese Đồng' },
  {
    countryName: 'West African Franc',
    code: 'XOF',
    currency: 'XOF',
    currencyName: 'West African CFA Franc',
  },
  { countryName: 'Yemen', code: 'YE', currency: 'YER', currencyName: 'Yemeni Rial' },
  { countryName: 'Zambia', code: 'ZM', currency: 'ZMW', currencyName: 'Zambian Kwacha' },
  {
    countryName: 'Zimbabwe (Unofficial)',
    code: 'ZW',
    currency: 'ZWG',
    currencyName: 'Zimbabwean Dollar (Unofficial)',
  },
  {
    countryName: 'Zimbabwe (Old)',
    code: 'ZW',
    currency: 'ZWL',
    currencyName: 'Zimbabwean Dollar (Old)',
  },
  {
    countryName: 'Central African Franc',
    code: 'XAF',
    currency: 'XAF',
    currencyName: 'Central African CFA Franc',
  },
  {
    countryName: 'Chilean Unidades de Fomento',
    code: 'CL',
    currency: 'CLF',
    currencyName: 'Chilean Unidades de Fomento',
  },
  {
    countryName: 'Caribbean Guilder',
    code: 'XC',
    currency: 'XCG',
    currencyName: 'Caribbean Guilder',
  },
  {
    countryName: 'East Caribbean Dollar',
    code: 'XC',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
  },
  {
    countryName: 'IMF Special Drawing Rights',
    code: 'XDR',
    currency: 'XDR',
    currencyName: 'IMF Special Drawing Rights',
  },
];
